#version: '2'
#
#services:
#  mongodb-dev-primary:
#    image: 'bitnami/mongodb:latest'
#    ports:
#      - "27017:27017"
#
#    volumes:
#      - ./mongodb_data:/bitnami
#
#    environment:
#      - MONGODB_ADVERTISED_HOSTNAME=localhost
#      - MONGODB_USERNAME=user1
#      - MONGODB_PASSWORD=pass1
#      - MONGODB_DATABASE=db1
##      - MONGODB_REPLICA_SET_MODE=primary
#      - MONGODB_ROOT_PASSWORD=rootpass1
##      - MONGODB_REPLICA_SET_KEY=replicasetkey123
##      - MONGODB_REPLICA_SET_NAME=rs1

version: '3.8'


services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
    - postgres
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=post123

  postgres:
    image: postgres:13
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post123
    volumes:
    - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: